Login:
   -
    by: id
    locator: main_item_user
    action: find
   -
    by: id
    locator: my_login_state_out_tv
    action: find
   -
    by: id
    locator: login_phone_et
    action: write
    value: 18721705015
   -
    by: id
    locator: login_btn
    action: find
   -
    by: id
    locator: login_btn
    action: find
    expression: